### ISSUE TITLE
Error when running the tool

### ISSUE THREAD

**Issue by mauricioaniche** [CodeIntelligenceTesting/jazzer#21]
Hi, all!

I am experimenting with jazzer, but so far I could not run it.

I try something simple as:

```
bazel run //:jazzer -- --cp=test-1.0-SNAPSHOT.jar --target_class=ch14.RandomStringUtilsFuzzer
```

But I get this output from the tool:

```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=160
INFO: Reading rc options for 'run' from /Users/mauricioaniche/tools/jazzer/.bazelrc:
  Inherited 'build' options: --incompatible_strict_action_env -c opt --cxxopt=-std=c++17 --action_env=CC=clang --java_language_version=8 --tool_java_language_version=9
ERROR: Unrecognized option: --java_language_version=8
```

I tried with java 8 and 11, but I get the same error. I'm on a Mac OS 10.15.7.

I am not really knowledagble in Bazel, so I might be making a novice mistake here.

Any ideas?

**Comment by fmeum** [comment]
Thanks for your interest in Jazzer!

Could you specify which version of Bazel you are using? Have you tried using the bazelisk binary included in the repository? 

Please note that we haven't tried running Jazzer on macOS yet. But since we want to support it eventually, I'm happy to help with any errors you should encounter.

**Comment by fmeum** [comment]
I have picked up work on macOS compatibility. With https://github.com/CodeIntelligenceTesting/jazzer/pull/22, you should be able to run most of the examples just fine.
