### ISSUE TITLE
Test Inputs Generation

### ISSUE THREAD

**Issue by miguelbpsg** [CodeIntelligenceTesting/jazzer#395]
I'm starting to use jazzer, but I am interested to know if there is any way to obtain as well the inputs that do not find crashes, that is, all the provided inputs for the target prior to the crash.

**Comment by fmeum** [comment]
Just like libFuzzer, Jazzer takes a corpus directory as an optional positional argument (see https://llvm.org/docs/LibFuzzer.html#running). Every input that triggers new coverage or other feedback from the instrumentation is added to the corpus.

Collecting *all* inputs is usually not a good idea since it hurts performance and generates very large amounts of data very quickly. If you still need this, e.g. to debug an issue that is caused by mutable global state and thus can't be reproduced with a single input, I would suggest writing the input to disk in your `fuzzerTestOneInput` function.
