### ISSUE TITLE
Add support for --coverage_report equivalent in JUnit integration

### ISSUE THREAD

**Issue by gredler** [CodeIntelligenceTesting/jazzer#475]
I'd love to be able to run fuzz tests more easily via the JUnit integration, but still receive a coverage report like the one that the binary is able to generate.

In the future I could also see myself needing equivalents for --coverage_dump, -merge, and -runs so I'm not sure if a one-to-one mapping to annotation parameters is ideal, or if something more generic (e.g. a "libFuzzerArgs" parameter and/or a "args" parameter) would be better.

**Comment by fmeum** [comment]
With IntelliJ Ultimate, you can actually just run the regression test "with coverage" (option on the play button) and you will get a report right in the IDE covering all corpus entries.

If you are using a different IDE, how are you usually determining coverage for your test suites? Ideally, that would cover `@FuzzTest`s too and we wouldn't need to introduce special handling for this important use case.

**Comment by gredler** [comment]
Yep, makes sense. Any thoughts on future plans for e.g. -merge or -runs?

**Comment by fmeum** [comment]
I think that `-runs` makes sense to expose on `@FuzzTest`, like we do with `maxDuration`. 

`-merge` is more difficult since that involves multiple corpora. What usecase for `-merge` do you have in mind?

**Comment by gredler** [comment]
Makes sense. I've been using -merge to save off different corpus directories at different stages and then merge them back into one corpus later on. I guess I was wondering more generally about all the LibFuzzer single-dash options, which the CLI docs seem to punt as "just go read the LibFuzzer docs and do whatever you want", so I was wondering if the same approach was planned here... -merge being the main place where I've taken advantage of this flexibility (so far).

**Comment by fmeum** [comment]
I don't have a fully fleshed out plan yet for how to deal with these "advanced" libFuzzer flags. I would like to keep them out of the `@FuzzTest` annotation, which should offer a friendly UX to users new to fuzzing. Instead, I'm thinking of making Jazzer available as a standalone JAR used from the CLI and/or making it possible to tune libFuzzer arguments via system properties.

I will close this issue as "not planned" for now since we will delegate coverage functionality to other tools that we intend to compose well with (e.g. JaCoCo), but will create a separate issue to track your `-merge` usecase.
